import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { buildReport } from "@/lib/report";
import type { GoalStatus } from "@/lib/database.types";

const STATUS_LABEL: Record<GoalStatus, string> = {
  on_track: "on track",
  at_risk: "at risk",
  behind: "behind",
  hit: "hit",
};

function deltaLabel(d: number | null): string {
  if (d == null) return "—";
  if (d > 0) return `▲ +${d}`;
  if (d < 0) return `▼ ${d}`;
  return "–";
}

export default async function ReportPage({ params }: { params: Promise<{ month: string }> }) {
  const { month } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/");

  const report = await buildReport(supabase);

  return (
    <main className="app">
      <div className="bar">
        <div className="brand">THE SHADOW FORUM</div>
        <nav className="nav">
          <Link href="/race">Race</Link>
          <Link href="/me">My Zone</Link>
        </nav>
        <div className="spacer" />
        <Link href="/profile" className="av">◧</Link>
      </div>

      <Link href="/race" className="back">← back to race</Link>

      <div className="race-head">
        <div>
          <div className="eyebrow">Monthly report</div>
          <h1>{decodeURIComponent(month)}</h1>
          <p className="sub">Auto-generated by the Steward + Chronicler.</p>
        </div>
      </div>

      <div className="report-movers">
        <div className="card">
          <h3>Biggest mover</h3>
          <p className="mover">{report.topMover ? `${report.topMover.name} ${deltaLabel(report.topMover.delta)}` : "—"}</p>
        </div>
        <div className="card">
          <h3>Biggest faller</h3>
          <p className="mover">{report.topFaller ? `${report.topFaller.name} ${deltaLabel(report.topFaller.delta)}` : "—"}</p>
        </div>
      </div>

      <section className="card" style={{ marginTop: 16 }}>
        <h3>Per-rider recap</h3>
        <table className="ladder">
          <thead>
            <tr>
              <th>Rider</th>
              <th className="r">Avg</th>
              <th className="r">Δ rank</th>
              <th>Goal</th>
              <th className="r">Owes</th>
            </tr>
          </thead>
          <tbody>
            {report.standings.map((r) => (
              <tr key={r.user_id}>
                <td>{r.name}</td>
                <td className="r">{r.avg || "—"}</td>
                <td className="r">{deltaLabel(r.delta)}</td>
                <td><span className={`chip ${r.goalStatus}`}>{STATUS_LABEL[r.goalStatus]}</span></td>
                <td className={`r amt ${r.owes === 0 ? "free" : "owe"}`}>{r.owes === 0 ? "0" : `${r.owes}M`}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </main>
  );
}
